USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/xiaomi/aries/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOOTLOADER_BOARD_NAME := MSM8960


TARGET_BOOTLOADER_BOARD_NAME := aries

BOARD_KERNEL_CMDLINE := console=null androidboot.hardware=qcom ehci-hcd.park=3 maxcpus=2 androidboot.bootdevice=msm_sdcc.1 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000

BOARD_BOOTIMAGE_PARTITION_SIZE := 15728640 
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640 
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912 
BOARD_USERDATAIMAGE_PARTITION_SIZE := 3758096384 
BOARD_FLASH_BLOCK_SIZE := 131072

DEVICE_RESOLUTION := 720x1280
RECOVERY_SDCARD_ON_DATA := true
TW_FLASH_FROM_STORAGE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_HAS_LOW_RESOLUTION := true
BRIGHTNESS_SYS_FILE := /sys/class/leds/lcd-backlight/brightness
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun/file
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_PREBUILT_KERNEL := device/xiaomi/aries/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
